intoduce substrate evm tools
subsquid/squid pull request #119
Opened 2022-09-22 21:02 UTC by belopash

2022-09-23 19:56 UTC, dzhelezov approved these changes
LGTM modulo error messages

2022-09-29 10:05 UTC, tmcgroul requested changes

2022-09-29 10:05 UTC, tmcgroul commented on util/substrate-frontier-evm/src/transaction.ts
> +import {Call, ChainContext, Event} from './interfaces'
`Event` is unused

2022-09-29 10:05 UTC, tmcgroul commented on util/substrate-frontier-evm/src/log.ts
> +import {assert} from 'console'
Shouldn't it be `import assert from 'assert'`?

2022-09-29 10:08 UTC, tmcgroul commented
@belopash Also please add a README

2022-09-29 12:46 UTC, merged