add `X-SQUID-ID` request header to processor requests
subsquid/squid pull request #80
Opened 2022-07-25 08:27 UTC by belopash

2022-07-25 11:07 UTC, mo4islona approved these changes

2022-07-28 12:13 UTC, eldargab requested changes
Please add the change files and change the HTTP headers type to `Record<string, string>`

2022-07-28 17:27 UTC, dzhelezov requested changes

2022-07-28 17:27 UTC, dzhelezov commented on substrate-processor/src/processor/runner.ts
> +                    'x-squid-id': process.env.SQUID_ID || 'unknown',
From @mo4islona:
Let's use `gen-{randomString(10)}` instead of `unknown`

2022-07-29 18:50 UTC, dzhelezov approved these changes

2022-07-29 19:29 UTC, mo4islona commented
> It will be regenerated on every request?
> 
> We should preserve it between restarts

Oh, I see. Def decorator caches the method

2022-07-29 21:40 UTC, merged