Gear support
subsquid/squid pull request #85
Opened 2022-07-27 14:32 UTC by tmcgroul

2022-07-28 12:38 UTC, eldargab requested changes

2022-07-28 12:38 UTC, eldargab commented on substrate-processor/src/processor/handlerProcessor.ts
> +                            hook: 'message-enqueued',
`gear-message-enqueued`

2022-07-28 12:38 UTC, eldargab commented on substrate-processor/src/processor/handlerProcessor.ts
> +                            hook: 'message-enqueued',
`gear-message-sent`

2022-07-28 14:39 UTC, dzhelezov commented on common/config/rush/pnpm-lock.yaml
> +      '@polkadot/api': ^8.11.3
Here we go again :( 
Is there any way to make this dependency optional only if the gear support is required? `pokadot/api` is really huge and including it as a dependency will make our squid images more heavy + it's know to be very volatile and not very stable.

2022-08-01 08:45 UTC, tmcgroul commented
note: the gear team reseted their testnet so the example project is broken:(

2022-08-04 12:43 UTC, merged